### ISSUE TITLE
Reordenar las animaciones del enemigo romano

### ISSUE THREAD

**Issue by FGonzalezLopez** [MercAddons/Walls-of-Valhalla#7]
Pues eso, ahora mismo creo que excepto la de muerte, están todas al revés.

**Comment by JJ** [comment]
Perdonad que me meta por medio, pero por favor, @FGonzalezLopez , pon tu ciudad en el perfil de GitHub para aparecer en los ránkings https://github.com/JJ/top-github-users-data/blob/master/formatted/top-Granada.md

**Comment by FGonzalezLopez** [comment]
Sin problemas :) . Ya está hecho, gracias.
